# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 24.x] # Specify the Node.js versions to test against
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        cache: ['yarn']

    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn check:env-safe
    - run: yarn build
      env:
        NX_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NX_PUBLIC_FIREBASE_API_KEY }}
        NX_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NX_PUBLIC_FIREBASE_AUTH_DOMAIN }}
        NX_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NX_PUBLIC_FIREBASE_PROJECT_ID }}
        NX_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NX_PUBLIC_FIREBASE_STORAGE_BUCKET }}
        NX_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NX_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
        NX_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NX_PUBLIC_FIREBASE_APP_ID }}
    - run: yarn build functions
    - run: yarn test --codeCoverage --coverageReporters=lcov --coverageDirectory=coverage
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
